### ISSUE TITLE
Unlock recipe book from inventory!

### ISSUE THREAD

**Issue by hunnaoduble0** [Declipsonator/Recipe-Unlocker#7]
This mod should work aswell whenever you open the recipe book from the Inventory and u don t necessarily have to be at a crafting table, this is a must!

**Comment by Declipsonator** [comment]
Pretty sure it does - is this feature not working?

**Comment by hunnaoduble0** [comment]
I'm on 1.21 and i can't see all recipes unless i'm at a crafting table.

**Comment by Declipsonator** [comment]
I can't replicate this issue

![image](https://github.com/Declipsonator/Recipe-Unlocker/assets/96392121/ca9f2d06-572d-45b6-a878-bf1052da63cc)

Can you send your game log?

**Comment by hunnaoduble0** [comment]
you just did it, in the picture it shows 10 pages and at a crafting tables it shows 26 pages.
![image](https://github.com/Declipsonator/Recipe-Unlocker/assets/173589549/60c24550-4796-4bc0-b874-dfcde5cb3759)

**Comment by hunnaoduble0** [comment]
> I can't replicate this issue
> 
> ![image](https://private-user-images.githubusercontent.com/96392121/344491609-ca9f2d06-572d-45b6-a878-bf1052da63cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MzYzMDcsIm5iZiI6MTcxOTkzNjAwNywicGF0aCI6Ii85NjM5MjEyMS8zNDQ0OTE2MDktY2E5ZjJkMDYtNTcyZC00NWI2LWE4NzgtYmYxMDUyZGE2M2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE2MDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMDYwZTgyNTY1MDcxYTA5Y2UzMTRiMmNjNGM2NDY3MTA2NGE0YjU2MDM0ZDljMWY2YWEyN2Q1OTQ1YWU0ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wSn2rswOLWn18OwXU-NgAtpVevQFmh-iMyx3_FxSpXA)
> 
> Can you send your game log?

https://paste.shockbyte.com/uyulagavujefebalabel.md

**Comment by Declipsonator** [comment]
The mod is working as intended. The recipes are unlocked but cannot be crafted from the inventory because they need 3x3 crafting space provided in the crafting table. It is not the mod's intention to change the crafting itself, just the recipe unlocking system.
